"""Deterministic scanner domain contracts."""

from market_trader.scanner.eligibility import (
    EligibilityEvaluator,
    EligibilityQuality,
)
from market_trader.scanner.engine import ScannerEngine
from market_trader.scanner.evidence import (
    BreadthEvidence,
    CatalystDirection,
    CatalystEvidence,
    CatalystMateriality,
    EvidenceValidationError,
    MacroEvidence,
    MacroState,
    SectorEvidence,
    SectorObservation,
    SupplementalEvidence,
    VolatilityDirection,
    VolatilityEvidence,
    parse_supplemental_evidence,
)
from market_trader.scanner.features import (
    FeatureCalculator,
    FeatureResult,
    FiveMinuteBar,
    assign_relative_performance_percentiles,
)
from market_trader.scanner.models import (
    CandidateResult,
    ComponentScore,
    Direction,
    EligibilityResult,
    EligibilityStatus,
    EvidenceRef,
    FeatureSet,
    GateResult,
    PolicyVersions,
    RegimeResult,
    RegimeState,
    ScanCounts,
    ScannerInput,
    ScanResult,
    StrategyResult,
    StrategyStatus,
    SymbolInput,
)
from market_trader.scanner.regime import RegimeClassifier
from market_trader.scanner.serialization import canonical_record, stable_digest

__all__ = [
    "BreadthEvidence",
    "CandidateResult",
    "CatalystDirection",
    "CatalystEvidence",
    "CatalystMateriality",
    "ComponentScore",
    "Direction",
    "EligibilityResult",
    "EligibilityStatus",
    "EligibilityEvaluator",
    "EligibilityQuality",
    "EvidenceRef",
    "EvidenceValidationError",
    "FeatureSet",
    "FeatureCalculator",
    "FeatureResult",
    "FiveMinuteBar",
    "GateResult",
    "MacroEvidence",
    "MacroState",
    "PolicyVersions",
    "RegimeClassifier",
    "RegimeResult",
    "RegimeState",
    "ScanCounts",
    "ScanResult",
    "ScannerInput",
    "ScannerEngine",
    "SectorEvidence",
    "SectorObservation",
    "StrategyResult",
    "StrategyStatus",
    "SupplementalEvidence",
    "SymbolInput",
    "VolatilityDirection",
    "VolatilityEvidence",
    "canonical_record",
    "assign_relative_performance_percentiles",
    "parse_supplemental_evidence",
    "stable_digest",
]
